package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallFlow;
import org.linlinjava.litemall.db.domain.LitemallFlowExample;

public interface LitemallFlowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flow
     *
     * @mbg.generated
     */
    long countByExample(LitemallFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flow
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flow
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flow
     *
     * @mbg.generated
     */
    int insert(LitemallFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flow
     *
     * @mbg.generated
     */
    int insertSelective(LitemallFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flow
     *
     * @mbg.generated
     */
    LitemallFlow selectOneByExample(LitemallFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flow
     *
     * @mbg.generated
     */
    LitemallFlow selectOneByExampleSelective(@Param("example") LitemallFlowExample example, @Param("selective") LitemallFlow.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flow
     *
     * @mbg.generated
     */
    List<LitemallFlow> selectByExampleSelective(@Param("example") LitemallFlowExample example, @Param("selective") LitemallFlow.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flow
     *
     * @mbg.generated
     */
    List<LitemallFlow> selectByExample(LitemallFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flow
     *
     * @mbg.generated
     */
    LitemallFlow selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") LitemallFlow.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flow
     *
     * @mbg.generated
     */
    LitemallFlow selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flow
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallFlow record, @Param("example") LitemallFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flow
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallFlow record, @Param("example") LitemallFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flow
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flow
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallFlow record);
}