package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallContract;
import org.linlinjava.litemall.db.domain.LitemallContractExample;

public interface LitemallContractMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_contract
     *
     * @mbg.generated
     */
    long countByExample(LitemallContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_contract
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_contract
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_contract
     *
     * @mbg.generated
     */
    int insert(LitemallContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_contract
     *
     * @mbg.generated
     */
    int insertSelective(LitemallContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_contract
     *
     * @mbg.generated
     */
    LitemallContract selectOneByExample(LitemallContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_contract
     *
     * @mbg.generated
     */
    LitemallContract selectOneByExampleSelective(@Param("example") LitemallContractExample example, @Param("selective") LitemallContract.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_contract
     *
     * @mbg.generated
     */
    LitemallContract selectOneByExampleWithBLOBs(LitemallContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_contract
     *
     * @mbg.generated
     */
    List<LitemallContract> selectByExampleSelective(@Param("example") LitemallContractExample example, @Param("selective") LitemallContract.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_contract
     *
     * @mbg.generated
     */
    List<LitemallContract> selectByExampleWithBLOBs(LitemallContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_contract
     *
     * @mbg.generated
     */
    List<LitemallContract> selectByExample(LitemallContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_contract
     *
     * @mbg.generated
     */
    LitemallContract selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallContract.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_contract
     *
     * @mbg.generated
     */
    LitemallContract selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_contract
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallContract record, @Param("example") LitemallContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_contract
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") LitemallContract record, @Param("example") LitemallContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_contract
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallContract record, @Param("example") LitemallContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_contract
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_contract
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(LitemallContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_contract
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallContract record);
}