package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallAudit;
import org.linlinjava.litemall.db.domain.LitemallAuditExample;

public interface LitemallAuditMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_audit
     *
     * @mbg.generated
     */
    long countByExample(LitemallAuditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_audit
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallAuditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_audit
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_audit
     *
     * @mbg.generated
     */
    int insert(LitemallAudit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_audit
     *
     * @mbg.generated
     */
    int insertSelective(LitemallAudit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_audit
     *
     * @mbg.generated
     */
    LitemallAudit selectOneByExample(LitemallAuditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_audit
     *
     * @mbg.generated
     */
    LitemallAudit selectOneByExampleSelective(@Param("example") LitemallAuditExample example, @Param("selective") LitemallAudit.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_audit
     *
     * @mbg.generated
     */
    List<LitemallAudit> selectByExampleSelective(@Param("example") LitemallAuditExample example, @Param("selective") LitemallAudit.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_audit
     *
     * @mbg.generated
     */
    List<LitemallAudit> selectByExample(LitemallAuditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_audit
     *
     * @mbg.generated
     */
    LitemallAudit selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallAudit.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_audit
     *
     * @mbg.generated
     */
    LitemallAudit selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_audit
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallAudit record, @Param("example") LitemallAuditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_audit
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallAudit record, @Param("example") LitemallAuditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_audit
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallAudit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_audit
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallAudit record);
}