package org.linlinjava.litemall.db.domain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class LitemallFlow {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_flow.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_flow.flow_num
     *
     * @mbg.generated
     */
    private String flowNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_flow.paid_integral
     *
     * @mbg.generated
     */
    private String paidIntegral;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_flow.total_integral
     *
     * @mbg.generated
     */
    private String totalIntegral;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_flow.paid_method
     *
     * @mbg.generated
     */
    private String paidMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_flow.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_flow.user_name
     *
     * @mbg.generated
     */
    private String userName;

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_flow.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_flow.id
     *
     * @return the value of litemall_flow.id
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_flow.id
     *
     * @param id the value for litemall_flow.id
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_flow.flow_num
     *
     * @return the value of litemall_flow.flow_num
     * @mbg.generated
     */
    public String getFlowNum() {
        return flowNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_flow.flow_num
     *
     * @param flowNum the value for litemall_flow.flow_num
     * @mbg.generated
     */
    public void setFlowNum(String flowNum) {
        this.flowNum = flowNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_flow.paid_integral
     *
     * @return the value of litemall_flow.paid_integral
     * @mbg.generated
     */
    public String getPaidIntegral() {
        return paidIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_flow.paid_integral
     *
     * @param paidIntegral the value for litemall_flow.paid_integral
     * @mbg.generated
     */
    public void setPaidIntegral(String paidIntegral) {
        this.paidIntegral = paidIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_flow.total_integral
     *
     * @return the value of litemall_flow.total_integral
     * @mbg.generated
     */
    public String getTotalIntegral() {
        return totalIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_flow.total_integral
     *
     * @param totalIntegral the value for litemall_flow.total_integral
     * @mbg.generated
     */
    public void setTotalIntegral(String totalIntegral) {
        this.totalIntegral = totalIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_flow.paid_method
     *
     * @return the value of litemall_flow.paid_method
     * @mbg.generated
     */
    public String getPaidMethod() {
        return paidMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_flow.paid_method
     *
     * @param paidMethod the value for litemall_flow.paid_method
     * @mbg.generated
     */
    public void setPaidMethod(String paidMethod) {
        this.paidMethod = paidMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_flow.user_id
     *
     * @return the value of litemall_flow.user_id
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_flow.user_id
     *
     * @param userId the value for litemall_flow.user_id
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_flow.create_time
     *
     * @return the value of litemall_flow.create_time
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_flow.create_time
     *
     * @param createTime the value for litemall_flow.create_time
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flow
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", flowNum=").append(flowNum);
        sb.append(", paidIntegral=").append(paidIntegral);
        sb.append(", totalIntegral=").append(totalIntegral);
        sb.append(", paidMethod=").append(paidMethod);
        sb.append(", userId=").append(userId);
        sb.append(", createTime=").append(createTime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flow
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LitemallFlow other = (LitemallFlow) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getFlowNum() == null ? other.getFlowNum() == null : this.getFlowNum().equals(other.getFlowNum()))
                && (this.getPaidIntegral() == null ? other.getPaidIntegral() == null : this.getPaidIntegral().equals(other.getPaidIntegral()))
                && (this.getTotalIntegral() == null ? other.getTotalIntegral() == null : this.getTotalIntegral().equals(other.getTotalIntegral()))
                && (this.getPaidMethod() == null ? other.getPaidMethod() == null : this.getPaidMethod().equals(other.getPaidMethod()))
                && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
                && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_flow
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getFlowNum() == null) ? 0 : getFlowNum().hashCode());
        result = prime * result + ((getPaidIntegral() == null) ? 0 : getPaidIntegral().hashCode());
        result = prime * result + ((getTotalIntegral() == null) ? 0 : getTotalIntegral().hashCode());
        result = prime * result + ((getPaidMethod() == null) ? 0 : getPaidMethod().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table litemall_flow
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "BIGINT", false),
        flowNum("flow_num", "flowNum", "VARCHAR", false),
        paidIntegral("paid_integral", "paidIntegral", "VARCHAR", false),
        totalIntegral("total_integral", "totalIntegral", "VARCHAR", false),
        paidMethod("paid_method", "paidMethod", "INTEGER", false),
        userId("user_id", "userId", "VARCHAR", false),
        createTime("create_time", "createTime", "TIMESTAMP", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_flow
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_flow
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_flow
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_flow
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_flow
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_flow
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_flow
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_flow
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_flow
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_flow
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_flow
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_flow
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_flow
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_flow
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_flow
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_flow
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}