package org.linlinjava.litemall.db.domain;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class LitemallCash {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_cash.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_cash.cash_num
     *
     * @mbg.generated
     */
    private String cashNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_cash.paid_amount
     *
     * @mbg.generated
     */
    private BigDecimal paidAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_cash.alipay_number
     *
     * @mbg.generated
     */
    private String alipayNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_cash.rem_balance
     *
     * @mbg.generated
     */
    private BigDecimal remBalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_cash.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_cash.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_cash.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_cash.created
     *
     * @mbg.generated
     */
    private LocalDateTime created;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_cash.id
     *
     * @return the value of litemall_cash.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_cash.id
     *
     * @param id the value for litemall_cash.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_cash.cash_num
     *
     * @return the value of litemall_cash.cash_num
     *
     * @mbg.generated
     */
    public String getCashNum() {
        return cashNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_cash.cash_num
     *
     * @param cashNum the value for litemall_cash.cash_num
     *
     * @mbg.generated
     */
    public void setCashNum(String cashNum) {
        this.cashNum = cashNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_cash.paid_amount
     *
     * @return the value of litemall_cash.paid_amount
     *
     * @mbg.generated
     */
    public BigDecimal getPaidAmount() {
        return paidAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_cash.paid_amount
     *
     * @param paidAmount the value for litemall_cash.paid_amount
     *
     * @mbg.generated
     */
    public void setPaidAmount(BigDecimal paidAmount) {
        this.paidAmount = paidAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_cash.alipay_number
     *
     * @return the value of litemall_cash.alipay_number
     *
     * @mbg.generated
     */
    public String getAlipayNumber() {
        return alipayNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_cash.alipay_number
     *
     * @param alipayNumber the value for litemall_cash.alipay_number
     *
     * @mbg.generated
     */
    public void setAlipayNumber(String alipayNumber) {
        this.alipayNumber = alipayNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_cash.rem_balance
     *
     * @return the value of litemall_cash.rem_balance
     *
     * @mbg.generated
     */
    public BigDecimal getRemBalance() {
        return remBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_cash.rem_balance
     *
     * @param remBalance the value for litemall_cash.rem_balance
     *
     * @mbg.generated
     */
    public void setRemBalance(BigDecimal remBalance) {
        this.remBalance = remBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_cash.user_id
     *
     * @return the value of litemall_cash.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_cash.user_id
     *
     * @param userId the value for litemall_cash.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_cash.type
     *
     * @return the value of litemall_cash.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_cash.type
     *
     * @param type the value for litemall_cash.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_cash.status
     *
     * @return the value of litemall_cash.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_cash.status
     *
     * @param status the value for litemall_cash.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_cash.created
     *
     * @return the value of litemall_cash.created
     *
     * @mbg.generated
     */
    public LocalDateTime getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_cash.created
     *
     * @param created the value for litemall_cash.created
     *
     * @mbg.generated
     */
    public void setCreated(LocalDateTime created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_cash
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", cashNum=").append(cashNum);
        sb.append(", paidAmount=").append(paidAmount);
        sb.append(", alipayNumber=").append(alipayNumber);
        sb.append(", remBalance=").append(remBalance);
        sb.append(", userId=").append(userId);
        sb.append(", type=").append(type);
        sb.append(", status=").append(status);
        sb.append(", created=").append(created);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_cash
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LitemallCash other = (LitemallCash) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCashNum() == null ? other.getCashNum() == null : this.getCashNum().equals(other.getCashNum()))
            && (this.getPaidAmount() == null ? other.getPaidAmount() == null : this.getPaidAmount().equals(other.getPaidAmount()))
            && (this.getAlipayNumber() == null ? other.getAlipayNumber() == null : this.getAlipayNumber().equals(other.getAlipayNumber()))
            && (this.getRemBalance() == null ? other.getRemBalance() == null : this.getRemBalance().equals(other.getRemBalance()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreated() == null ? other.getCreated() == null : this.getCreated().equals(other.getCreated()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_cash
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCashNum() == null) ? 0 : getCashNum().hashCode());
        result = prime * result + ((getPaidAmount() == null) ? 0 : getPaidAmount().hashCode());
        result = prime * result + ((getAlipayNumber() == null) ? 0 : getAlipayNumber().hashCode());
        result = prime * result + ((getRemBalance() == null) ? 0 : getRemBalance().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreated() == null) ? 0 : getCreated().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table litemall_cash
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "BIGINT", false),
        cashNum("cash_num", "cashNum", "VARCHAR", false),
        paidAmount("paid_amount", "paidAmount", "DECIMAL", false),
        alipayNumber("alipay_number", "alipayNumber", "VARCHAR", false),
        remBalance("rem_balance", "remBalance", "DECIMAL", false),
        userId("user_id", "userId", "BIGINT", false),
        type("type", "type", "VARCHAR", true),
        status("status", "status", "VARCHAR", true),
        created("created", "created", "TIMESTAMP", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_cash
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_cash
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_cash
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_cash
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_cash
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_cash
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_cash
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_cash
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_cash
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_cash
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_cash
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_cash
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_cash
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_cash
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_cash
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_cash
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}